### PR TITLE
Miasm2 404

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by radare** [comment]
I tried to use sibyl, but, i had the same experience i have always i try something in python.

* dependencies not properly defined
* wrong module names (miasm2 vs miasm)
* camelcase issues in module names related to HFS+
* No python3 support

So i did some of the changes needed to get this in shape. The py3 port is not as easy as adding () to the prints. because the current code is using utf8 strings to hold binary data, which will require more work to fix, and probably a testsuite, or a working starting point (which i dont have because i get stacktraces all the time)

**Comment by radare** [comment]
btw https://github.com/radare/radare2-pm/blob/master/db/sibyl

**Comment by commial** [comment]
Hi,
First, thanks for your interest for Sibyl.
Indeed, the project Miasm is moving from `miasm2` to `miasm`, with support for both Python2 / Python3.

But, as stated in the Sibyl README:
> Sibyl requires at least Miasm2 version v0.1.1

So, after cloning Miasm, one should use the exact version and not the current master branch:
`git checkout v0.1.1`
Which should work (it is indeed enforced in the Travis CI: https://github.com/cea-sec/Sibyl/blob/master/.travis.yml).

The support for Python3 will arrive in the next version, now that Miasm supports it.

**Comment by radare** [comment]
Ouch. Ok now i understand why i wasnt able to find out the right module here.

Python2 will die in half a year. And cloning a very old version of miasm is probably going to give a lot of headaches to get it working (already sent some fixes to miasm because it was not even able to compile it on macOS).

Do you have plans to update it to py3 and latest miasm?

**Comment by commial** [comment]
To be honest, v0.1.1 is still the latest version of Miasm, released 3 months ago (not sure it is already "very old").
But you're right, Python2 is dying.
So, we first need to have Miasm released with Python3 support, which will probably arrive very soon. Then, we will be able to add the support to Sibyl, which is quite a big work (see https://github.com/cea-sec/miasm/pull/990). Fortunately, we learn quite a few tricks along the path, so  I hope there will be not so many difficulties.

Hope the Python2 version is working for your needs.

**Pull request closed without merging**
