### PR TITLE
Update func.py

### PR DESCRIPTION
**Pull request by Vitaly-Protasov**
Fixed some errors with importing

### CODE REVIEW

**Comment by p-l-** [comment]
Hi,

I'm not sure what you are fixing here. Could you provide an example of code currently broken that this PR would fix?

**Comment by Vitaly-Protasov** [comment]
> Hi,
> 
> I'm not sure what you are fixing here. Could you provide an example of code currently broken that this PR would fix?

In the file /heuristics/func.py 
still using "loc_db" without importing class LocationDB from mism2 and without defineding loc_db as loc_db=LocationDB()

Am I wrong?

**Comment by p-l-** [comment]
Do you currently have an example of code that triggers the bug you are trying to fix?

> Am I wrong?

I think you are, that's why I'm asking. `loc_db` does not need to be imported, since it comes from `func_heur.cont.loc_db`.

**Comment by Vitaly-Protasov** [comment]
Sure, if you take a look at https://github.com/cea-sec/Sibyl/tree/master/sibyl/heuristics/func.py
You can notice that there is "loc_db", but it was not defined there and didn't import from other files.

**Comment by p-l-** [comment]
`loc_db` is defined at line 20 in `recursive_call()` from `cont.loc_db`, so it does not need to be defined. Same at line 116.

Again, do you have an example of Python stacktrace complaining about an undefined variable that you are trying to fix here?

**Comment by Vitaly-Protasov** [comment]
Sorry for disturbing. I used the version of Sibyl where this problem wasn't fix. 

Btw, could you guess me workable version of miasm for sibyl? 
Because I can't find the version where at sibyl works more than only "sibyl find"

**Comment by commial** [comment]
The main part of Sibyl, ie `sibyl find`, should be working with Miasm latest version.
The R&D part on learning needs an API update (see #85).
If you want a fully working Sibyl, you can refer to releases (which is only v0.1 for now) and associated Miasm version (which was, at this time, a commit id in the README).

**Pull request closed without merging**
