### PR TITLE
Fix memcpy/memmove

### PR DESCRIPTION
**Pull request by serpilliere**

### CODE REVIEW

**Comment by commial** [comment]
You need a test to differentiate `memcpy` and `memmove` in `memcpy`, which is currently only a subpart of `TestMemmove`. Otherwise, each time a `memmove` will be spotted, a `memcpy` will also pop up.

In addition, if you want your test active, you must add it to the variable `TESTS` at the end of the script

**Comment by serpilliere** [comment]
I agree with you for the `memcpy`. But I didn't found any trivial tests which can do the difference: the memcpy can be done up or down. Moreover, is it really a problem to have two responses in the test?

**Comment by commial** [comment]
I think that if we can avoid a trivial false positive, we should. I also agree with you on the difficulty to test memcpy.

What you think if I add the capability for a test to dismiss another one if it success ?
Or if the second test succeses, you can change the funcname to memmove.

**Comment by serpilliere** [comment]
Instead of the mechanism you propose, maybe it may be interesting to give a test the chance to a combination of checks.

For the `memcopy` example, we have the main test (say TEST1), we can and two more tests: one for testing the copy in growing addresses (say TEST2), another by testing the copy in descending addresses (say TEST3). The global test successes in case of: `TEST1 & (!TEST2 or !TEST3)`.

This may resolve more generic cases than the link between two functions which excludes.

**Comment by commial** [comment]
Right, I agree with your version.

I'll work on a way to handle this kind of condition while taking benefit of Python lazy evaluation to avoid launching unnecessary test cases (in Sibyl, it could be a real performance issue).

**Comment by serpilliere** [comment]
Good idea.
I will update the PR when the feature will be integrated.

**Comment by commial** [comment]
Following this idea, this same kind of test could be used in the future to launch tests only on some precondition.
For instance, we can easily imagine a basic pointer type prediction using the fact that if an argument is directly use to access memory, it must be a pointer (the inverse is not True, of course).

That way, tests like `atoi` could include a success test as `!is_pointer(arg1) & TEST1`.
The `is_pointer` will be enhanced with each test case attempt, avoiding some emulation in potentially many cases.

**Pull request merged**
